/* MoEngage Agentic Brain Terminal — vanilla runtime over the brain API. No external resources (CSP self-only). */
(() => {
'use strict';
const TOKEN = (document.querySelector('meta[name="local-token"]') || {}).content || '';
const $ = (s, r = document) => r.querySelector(s);
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]));
const fmt = (n, d = 2) => (n === null || n === undefined || n === '' || isNaN(Number(n))) ? '—' : Number(n).toLocaleString(undefined, {maximumFractionDigits: d});
const pct = (n, d = 1) => (n === null || n === undefined || isNaN(Number(n))) ? '—' : `${Number(n) > 0 ? '+' : ''}${Number(n).toFixed(d)}%`;
const cls = (n) => Number(n) > 0 ? 'up' : Number(n) < 0 ? 'down' : 'flat';
const C = {cy: '#6fe3ff', dim: '#7fd8ec', gr: '#4dffa8', am: '#ffb84d', mg: '#ff5c9e', txt: '#d3e7ef'};
const NAV = [
  {id: 'brain', code: '01', label: 'BRAIN', title: 'Brain', crumb: 'ENGINE / CORE', sub: 'Live cognition state, ranked directives and everything the brain decided in the last cycle.'},
  {id: 'lab', code: '02', label: 'BRAIN LAB', title: 'Brain Lab', crumb: 'ENGINE / INTEL', sub: 'Money flow, trader behaviour, rivals that matter, markets and world events distilled into recommendations. Internal only: no venue is ever named in copy.'},
  {id: 'ideas', code: '03', label: 'CAMPAIGN IDEAS', title: 'Campaign Ideas', crumb: 'ENGINE / IDEATION', sub: 'Hypotheses scored with ICE (impact × confidence × ease), structural gaps first. Stale ideas expire on their own.'},
  {id: 'exp', code: '04', label: 'EXPERIMENTS', title: 'Experiments', crumb: 'ENGINE / EXPERIMENTS', sub: 'Idea → simulation → approval → live → learning, ranked by ICE. Every proposal is an experiment; nothing sends without a human.'},
  {id: 'sops', code: '05', label: 'SOP LIBRARY', title: 'Campaign SOPs', crumb: 'ENGINE / SOPS', sub: 'Versioned operating procedures per campaign family: sequence, caps, holdout, kill rules.'},
  {id: 'anom', code: '06', label: 'ANOMALIES', title: 'Anomalies', crumb: 'ENGINE / TELEMETRY', sub: 'Daily snapshots diffed against each campaign’s own baseline, ranked by urgency, with the cause and the option that comes first.'},
  {id: 'atlas', code: '07', label: 'COHORTS', title: 'Cohorts', crumb: 'ENGINE / COHORTS', sub: 'Every uploaded segment decoded by its nomenclature, mapped to products, stages, touch budgets and the peace index.'},
];
const ALIAS = {intel: 'lab', market: 'lab', competitors: 'lab', cohorts: 'atlas'};
const S = {screen: 'brain', state: null, sop: null, sops: [], filter: 'all', trace: [], focus: 0, directives: [], busy: false, seenTrace: new Set()};
try { S.scan = localStorage.getItem('moe.scan') !== 'off'; } catch (_) { S.scan = true; }
document.body.classList.toggle('noscan', !S.scan);

async function api(path, {method = 'GET', body} = {}) {
  const init = {method, headers: {'X-Local-Token': TOKEN}};
  if (body !== undefined) { init.headers['Content-Type'] = 'application/json'; init.body = JSON.stringify(body); }
  const r = await fetch(path, init); let data = null; try { data = await r.json(); } catch (_) {}
  if (r.status === 401) { toast('server restarted · reload the page for a fresh session token', 'warn', 9000); throw new Error('session token expired'); }
  if (!r.ok) { const m = (data && (data.detail || data.error)) || `${r.status} ${r.statusText}`; throw new Error(typeof m === 'string' ? m : JSON.stringify(m)); }
  return data;
}
function toast(msg, type = 'error', ms = 5000) { const t = document.createElement('div'); t.className = `toast ${type}`; t.textContent = msg; $('#toasts').appendChild(t); setTimeout(() => t.remove(), ms); }
function pushTrace(text, level = 'info') { const d = new Date(); const ts = [d.getHours(), d.getMinutes(), d.getSeconds()].map(x => String(x).padStart(2, '0')).join(':'); S.trace.push({ts, text, level, local: true}); S.trace = S.trace.slice(-40); renderTrace(); }
const loading = () => `<div class="panel"><div class="ph"><span class="t">loading</span></div><div class="loading"><div class="dash"></div></div></div>`;
const empty = (fact, next) => `<div class="empty"><b>${esc(fact)}</b>${next ? ` · ${esc(next)}` : ''}</div>`;
const err = (m) => `<div class="err">${esc(m)}</div>`;
const md = (src) => { let h = esc(src || ''); h = h.replace(/^### (.*)$/gm, '<b>$1</b>').replace(/^## (.*)$/gm, '<b>$1</b>').replace(/^# (.*)$/gm, '<b>$1</b>').replace(/\*\*(.+?)\*\*/g, '<b>$1</b>').replace(/`([^`]+)`/g, '<code>$1</code>').replace(/^\s*[-•] (.*)$/gm, '<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g, m => `<ul>${m}</ul>`).replace(/\n{2,}/g, '</p><p>').replace(/\n/g, '<br>'); return `<div class="md"><p>${h}</p></div>`; };

// ── chrome ────────────────────────────────────────────────────────────────────
function tick() { const d = new Date(); $('#clock').textContent = [d.getHours(), d.getMinutes(), d.getSeconds()].map(x => String(x).padStart(2, '0')).join(':'); }
setInterval(tick, 1000); tick();
function renderChrome() {
  const st = S.state || {}; const cur = NAV.find(n => n.id === S.screen) || NAV[0];
  $('#bus').innerHTML = (st.bus || []).map(b => `<div class="chip"><span class="k">${esc(b.k)}</span><span class="v" style="color:${esc(b.c)}">${esc(b.v)}</span></div>`).join('');
  const badges = st.badges || {};
  $('#nav').innerHTML = NAV.map(n => `<button class="item ${n.id === S.screen ? 'on' : ''}" data-go="${n.id}"><span class="code">${n.code}</span><span>${n.label}</span>${badges[n.id] ? `<span class="badge">${badges[n.id]}</span>` : ''}</button>`).join('');
  $('#load').innerHTML = (st.load || []).map(l => `<div class="meter" title="${esc(l.note || '')}"><div class="r"><span>${esc(l.name)}</span><span style="color:${esc(l.c)}">${esc(l.val)}</span></div><div class="bar"><i style="width:${l.pct}%;background:${esc(l.c)}"></i></div></div>`).join('');
  $('#facts').textContent = `bind 127.0.0.1 · secrets keychain · region ${st.region || '—'}`;
  $('#crumb').textContent = cur.crumb; $('#h1').textContent = cur.title; $('#sub').textContent = cur.sub;
  const on = !!st.autopilot; const t = $('#auto'); t.classList.toggle('on', on); t.setAttribute('aria-pressed', String(on)); $('#auto-lab').textContent = on ? 'ON · approval still required for sends' : 'OFF';
  const stats = (st.stats || {})[S.screen] || [];
  $('#strip').innerHTML = stats.length ? stats.map(s => `<div class="tile"><div class="k">${esc(s.k)}</div><div class="v" style="color:${esc(s.c || C.txt)}">${esc(s.v)}</div><div class="s">${esc(s.sub || '')}</div></div>`).join('') : `<div class="tile"><div class="k">STATE</div><div class="v">—</div><div class="s">loading</div></div>`;
  $('#scan-toggle').textContent = `scanlines: ${S.scan ? 'on' : 'off'}`;
}
async function refreshState() { try { S.state = await api('/api/brain/state'); renderChrome(); } catch (e) { if (!S.state) $('#strip').innerHTML = `<div class="tile"><div class="k">STATE</div><div class="v" style="color:${C.mg}">unreachable</div><div class="s">${esc(e.message)}</div></div>`; } }

// ── modules ───────────────────────────────────────────────────────────────────
const views = {};
views.brain = async () => {
  const body = $('#body'); body.innerHTML = `<div class="cols"><div class="c3"><div class="panel"><div class="ph"><span class="t">Priority directives</span><span class="meta">ranked by severity · a approves the focused one</span></div><div id="dirs">${loading()}</div></div>
    <div class="panel"><div class="ph"><span class="t">Cognition pipeline</span><span class="meta">this cycle</span></div><div class="pb pipe" id="pipe"></div></div></div>
    <div class="c2"><div class="panel"><div class="ph"><span class="t">Brain trace · live</span><span class="meta">audit log · receipts</span></div><div class="trace" id="trace"></div></div>
    <div class="panel"><div class="ph"><span class="t">Morning brief</span><span class="meta">plain english</span></div><div class="pb brief" id="brief"></div></div></div></div>`;
  renderPipeline(); renderBrief(); renderTrace();
  try { const d = await api('/api/brain/directives'); S.directives = d.directives || []; S.focus = 0; renderDirectives(); } catch (e) { $('#dirs').innerHTML = err(e.message); }
};
function renderPipeline() { const p = (S.state || {}).pipeline || []; const el = $('#pipe'); if (!el) return; el.innerHTML = p.map(x => `<div class="st"><div class="lab10">${esc(x.stage)}</div><div class="n" style="color:${esc(x.c)}">${esc(x.count)}</div><div class="bar"><i style="width:${x.pct}%;background:${esc(x.c)}"></i></div><div class="note">${esc(x.note)}</div></div>`).join(''); }
function renderBrief() { const b = (S.state || {}).brief || []; const el = $('#brief'); if (!el) return; const col = {act_now: C.mg, high_ev: C.cy, counter: C.am, cleanup: C.gr, watch: C.am, good: C.gr, info: C.dim}; el.innerHTML = b.length ? b.map(x => `<div class="b"><span class="g" style="color:${col[x.sev] || C.dim}">▸</span><span>${esc(x.t)}</span></div>`).join('') : empty('no brief yet', 'run the daily cycle'); }
function renderDirectives() {
  const el = $('#dirs'); if (!el) return; const ds = S.directives;
  el.innerHTML = ds.length ? ds.map((d, i) => `<div class="dir ${i === S.focus ? 'focus' : ''}" data-i="${i}"><div class="railx" style="background:${esc(d.color)}"></div><div class="bd"><span class="chip sev" style="color:${esc(d.color)};border-color:${esc(d.color)}">${esc(d.sev_label)}</span><div class="tt">${esc(d.title)}</div><div class="mm">${esc(d.meta)}</div><div class="rr">${esc(d.rationale)}</div>
    <div class="ac">${d.actions.includes('approve') ? `<button class="btn sm g" data-act="approve" data-id="${esc(d.id)}">Approve + execute</button>` : ''}${d.actions.includes('simulate') ? `<button class="btn sm c" data-act="simulate" data-id="${esc(d.id)}">Simulate</button>` : ''}${d.actions.includes('hold') ? `<button class="btn sm m" data-act="hold" data-id="${esc(d.id)}">Hold</button>` : ''}<button class="btn sm" data-ask="${esc(d.id)}">Ask the brain</button></div><div class="sim" id="sim-${i}"></div></div></div>`).join('') : empty('no directives right now', 'next cycle at ' + (((S.state || {}).bus || []).find(b => b.k === 'SCHEDULER') || {}).v);
}
async function actDirective(id, action, i) {
  if (action === 'approve' && !confirm('Approve and execute? The previewed write will be sent to MoEngage.')) return;
  const note = action === 'hold' ? (prompt('Why hold it? (recorded on the proposal)') || '') : '';
  try {
    const r = await api(`/api/brain/directives/${encodeURIComponent(id)}/${action}`, {method: 'POST', body: {note}});
    pushTrace(r.trace || `directive/${action} ${id}`, r.ok ? (action === 'approve' ? 'ok' : 'info') : 'alert');
    if (r.error) toast(r.error);
    const box = $(`#sim-${i}`);
    if (box && action === 'simulate') box.innerHTML = `<div class="hair" style="margin-top:8px;padding-top:8px;font-size:11px;color:#93aab7">${r.brief_check ? `brief ${r.brief_check.ok ? '<span class="up">ok</span>' : '<span class="down">problems</span>'} ${esc((r.brief_check.problems || []).join('; '))} ${esc((r.brief_check.warnings || []).slice(0, 2).join('; '))}` : ''}${r.preview ? ` · preview <code>${esc(r.preview.mode || '')}</code> ${esc(r.preview.transport || '')}` : ''}${r.diagnosis ? `<div>${esc(((r.diagnosis.options || [])[0] || {}).action || '')} — ${esc(((r.diagnosis.options || [])[0] || {}).how_in_moengage || '')}</div>` : ''}${r.pair_battle ? `<div>${(r.pair_battle.venues || []).slice(0, 5).map(v => `${esc(v.exchange)} ${fmt(v.share_pct, 0)}%`).join(' · ')}</div>` : ''}${r.agent_prompt ? `<div><button class="btn sm c" data-ask-text="${esc(r.agent_prompt)}">Hand to the brain</button></div>` : ''}</div>`;
    if (action !== 'simulate') { await refreshState(); await views.brain(); }
  } catch (e) { toast(e.message); pushTrace(`directive/${action} failed · ${e.message}`, 'alert'); }
}
function renderTrace() { const el = $('#trace'); if (!el) return; el.innerHTML = S.trace.map(l => `<div class="ln"><span class="ts">${esc(l.ts)}</span><span class="tx lv-${esc(l.level)}">${esc(l.text)}</span></div>`).join('') + `<div class="ln"><span class="ts"></span><span class="cursor"></span></div>`; el.scrollTop = el.scrollHeight; }
async function pollTrace() { try { const d = await api('/api/brain/trace?limit=40'); const server = (d.lines || []).map(l => ({...l, key: l.ts + '|' + l.text})); const local = S.trace.filter(l => l.local); S.trace = [...server, ...local].slice(-40); renderTrace(); } catch (_) {} }

const money = (v) => v == null ? '—' : Math.abs(v) >= 1e9 ? (v < 0 ? '-' : '') + '$' + fmt(Math.abs(v) / 1e9, 2) + 'B' : Math.abs(v) >= 1e6 ? (v < 0 ? '-' : '') + '$' + fmt(Math.abs(v) / 1e6, 1) + 'M' : '$' + fmt(v, 0);
const urgC = {alert: C.mg, warn: C.am, good: C.gr, info: C.dim};
const signed = (v, d = 1) => v == null ? '—' : `${v > 0 ? '+' : ''}${fmt(v, d)}`;
S.mkCat = S.mkCat || 'crypto'; S.showMinor = false;
views.lab = async () => {
  const body = $('#body'); body.innerHTML = loading();
  try {
    const d = await api('/api/brain/lab'); S.lab = d;
    const f = d.flow || {}; const ra = f.risk_appetite || {}; const raC = ra.label === 'risk-on' ? C.gr : ra.label === 'risk-off' ? C.mg : C.am;
    const st = f.stablecoins || {}; const rot = f.rotation || {}; const lev = f.leverage || {}; const vs = f.venue_share || {}; const dom = f.dominance || {}; const w3 = f.web3 || {};
    const mk = d.market || {}; const rv = d.rivals || {}; const ev = d.events || {};
    const readsHtml = `<div class="panel"><div class="ph"><span class="t">What traders are doing today</span><span class="meta">behaviour reads · evidence first · ${f.history_days || 0}d of own history</span></div><div class="pb"><div class="cards">${(d.reads || []).map(r => `<div class="card"><div class="nm" style="font-size:13px"><span>${esc(r.read)}</span><span class="chip" style="color:${r.confidence === 'high' ? C.gr : r.confidence === 'low' ? 'var(--text-ghost)' : C.am}">${esc(r.confidence)}</span></div><div class="mv">${esc(r.evidence)}</div><div class="foot"><span class="lab10">so traders</span><span style="text-align:right;color:${C.cy}">${esc(r.traders_do)}</span></div></div>`).join('') || empty('no reads yet')}</div></div></div>`;
    const gauge = `<div class="panel"><div class="ph"><span class="t">Risk appetite</span><span class="meta">composite 0–100</span></div><div class="pb"><div class="pi"><div class="r"><span style="color:${raC};font:600 22px/1 var(--display)">${ra.score ?? '—'}</span><span class="chip sev" style="color:${raC};border-color:${raC}">${esc((ra.label || '—').toUpperCase())}</span></div><div class="bar"><i style="width:${ra.score || 0}%;background:${raC}"></i></div></div><div class="ghost" style="font-size:10px;margin-top:6px">${(ra.reasons || []).map(esc).join(' · ')}</div>
      <div class="lab10" style="margin:12px 0 4px">dominance</div><div style="font-size:12px">BTC <b>${fmt(dom.btc, 1)}%</b> <span class="${cls(dom.btc_chg_1d_pp)}">${dom.btc_chg_1d_pp != null ? signed(dom.btc_chg_1d_pp, 2) + ' pp/d' : '(history builds daily)'}</span> · ETH <b>${fmt(dom.eth, 1)}%</b><div class="ghost" style="font-size:10px">total cap ${money(dom.total_mcap_usd)} · <span class="${cls(dom.mcap_chg_24h_pct)}">${pct(dom.mcap_chg_24h_pct)}</span> 24h · regime ${esc(f.regime || '—')}</div></div>
      <div class="lab10" style="margin:12px 0 4px">leverage</div><div style="font-size:12px">perp OI ${money(lev.hl_oi_usd)} <span class="${cls(lev.oi_chg_1d_pct)}">${lev.oi_chg_1d_pct != null ? pct(lev.oi_chg_1d_pct) + ' 1d' : ''}</span><div class="ghost" style="font-size:10px">crowded long: ${(lev.crowded_long || []).map(esc).join(', ') || 'none'} · crowded short: ${(lev.crowded_short || []).map(esc).join(', ') || 'none'}</div></div></div></div>`;
    const recsHtml = `<div class="panel"><div class="ph"><span class="t">Recommendations · ranked by ICE</span><span class="meta">P0 = structural miss in the CRM journey · who · what · sop · kpi · avoid</span></div><div class="pb">${(d.recommendations || []).map((r, i) => `<div class="an" style="align-items:flex-start"><div><span class="chip sev" style="color:${r.structural ? C.mg : r.priority >= 85 ? C.mg : r.priority >= 65 ? C.am : C.cy};border-color:${r.structural ? C.mg : r.priority >= 85 ? C.mg : r.priority >= 65 ? C.am : C.cy}">${r.structural ? 'P0' : 'P' + r.priority}</span> <span class="nm">${esc(r.title)}</span> ${r.ice ? `<span class="ice">ICE ${r.ice.score} <span class="ghost">${r.ice.impact}·${r.ice.confidence}·${r.ice.ease}</span></span>` : ''} <span class="mt">${esc(r.urgency)}${r.product ? ' · ' + esc(r.product) : ''}</span>${r.tagline ? `<div class="tagline">${esc(r.tagline)}</div>` : ''}<div class="ca"><span class="lab10">why ·</span> ${esc(r.why)}</div><div class="op"><span class="lab10">who ·</span> ${esc(r.who)} <span class="lab10" style="margin-left:8px">what ·</span> ${esc(r.what)}</div><div class="ghost" style="font-size:10px;margin-top:3px">kpi ${esc(r.kpi)}${r.benchmark ? ' · benchmark ' + esc(r.benchmark) : ''}${r.avoid ? ' · avoid: ' + esc(r.avoid) : ''}</div></div>
      <div class="rt"><div class="mono" style="font-size:10px;color:var(--text-mute)">${esc((r.sop || 'no sop').replace('sop_', ''))}</div>${r.sop ? `<button class="btn sm c" style="margin-top:4px" data-ask-text="Execute recommendation: ${esc(r.title)}. Why: ${esc(r.why)}. Audience: ${esc(r.who)}. Plan: ${esc(r.what)}. Use run_sop('${esc(r.sop)}') dry-run first, two compliant variants, respect regime, comms limits and peace index; avoid ${esc(r.avoid || 'promos')}; no venue names. KPI: ${esc(r.kpi)}. Carry ICE impact ${(r.ice || {}).impact || 5}, confidence ${(r.ice || {}).confidence || 5}, ease ${(r.ice || {}).ease || 5} and the tagline into the proposal.">Ask the brain</button>` : ''}</div></div>`).join('') || empty('no recommendations')}</div></div>`;
    const flowHtml = `<div class="panel"><div class="ph"><span class="t">Money flow · where capital is going</span><span class="meta">${(f.sources || []).map(esc).join(' · ')}</span></div><div class="pb"><div class="cols">
      <div class="c1"><div class="lab10" style="margin-bottom:4px">stablecoins · dry powder</div><div style="font-size:12px">supply <b>${money(st.total_now_usd)}</b><div>1d <span class="${cls(st.net_1d_usd)}">${money(st.net_1d_usd)}</span> · 7d <span class="${cls(st.net_7d_usd)}">${money(st.net_7d_usd)}</span></div></div><div class="ghost" style="font-size:10px;margin:4px 0">${(st.top || []).map(s => `${esc(s.symbol)} ${money(s.now_usd)} (${money(s.chg_7d_usd)} 7d)`).join(' · ')}</div><div class="lab10" style="margin:8px 0 2px">chains gaining · 7d</div>${(st.chains_in || []).map(c => `<div style="display:flex;justify-content:space-between;font-size:11px;padding:2px 0;border-bottom:1px solid var(--line-soft)"><span>${esc(c.chain)}</span><span class="${cls(c.chg_7d_usd)}">${money(c.chg_7d_usd)}</span></div>`).join('')}<div class="lab10" style="margin:8px 0 2px">chains losing</div>${(st.chains_out || []).filter(c => c.chg_7d_usd < 0).map(c => `<div style="display:flex;justify-content:space-between;font-size:11px;padding:2px 0;border-bottom:1px solid var(--line-soft)"><span>${esc(c.chain)}</span><span class="down">${money(c.chg_7d_usd)}</span></div>`).join('') || '<div class="ghost" style="font-size:11px">none</div>'}</div>
      <div class="c1"><div class="lab10" style="margin-bottom:4px">sector rotation · in (24h cap change)</div>${(rot.in || []).slice(0, 6).map(c => `<div style="display:flex;justify-content:space-between;font-size:11px;padding:2px 0;border-bottom:1px solid var(--line-soft)"><span>${esc(c.tag)} <span class="ghost">${(c.top || []).slice(0, 2).map(esc).join(', ')}</span></span><span class="${cls(c.chg_24h_pct)}">${pct(c.chg_24h_pct)}</span></div>`).join('') || '<div class="ghost" style="font-size:11px">—</div>'}<div class="lab10" style="margin:8px 0 4px">out</div>${(rot.out || []).slice(0, 5).map(c => `<div style="display:flex;justify-content:space-between;font-size:11px;padding:2px 0;border-bottom:1px solid var(--line-soft)"><span>${esc(c.tag)} <span class="ghost">${(c.top || []).slice(0, 2).map(esc).join(', ')}</span></span><span class="${cls(c.chg_24h_pct)}">${pct(c.chg_24h_pct)}</span></div>`).join('') || '<div class="ghost" style="font-size:11px">—</div>'}<div class="ghost" style="font-size:10px;margin-top:4px">${esc(rot.source || '')} · ${rot.count || 0} sectors ≥ $3B</div></div>
      <div class="c1"><div class="lab10" style="margin-bottom:4px">venue volume share · asset class</div>${Object.entries(vs.now || {}).map(([k, v]) => `<div class="sov"><div class="r"><span>${esc(k.replace('_', ' '))}</span><span>${fmt(v, 1)}%${vs.week_ago && vs.week_ago[k] != null ? ` <span class="ghost">(${fmt(vs.week_ago[k], 1)}% wk ago)</span>` : ''}</span></div><div class="bar"><i style="width:${Math.min(100, v)}%;background:${k === 'crypto' ? C.cy : k === 'us_stocks' ? C.am : k === 'commodities' ? C.gr : C.mg}"></i></div></div>`).join('')}<div class="ghost" style="font-size:10px;margin:4px 0 8px">${esc(vs.note || '')}</div>
        <div class="lab10" style="margin-bottom:4px">attention spikes · vs 7-day avg</div>${(f.attention || []).slice(0, 8).map(a => `<div style="display:flex;justify-content:space-between;font-size:11px;padding:2px 0;border-bottom:1px solid var(--line-soft)"><span><b>${esc(a.symbol)}</b> <span class="ghost">${esc(a.asset_class)}</span></span><span>${a.vs_7d_avg_x}× <span class="${cls(a.chg_24h)}">${pct(a.chg_24h)}</span></span></div>`).join('') || '<div class="ghost" style="font-size:11px">needs 2+ days of history (builds automatically)</div>'}
        <div class="lab10" style="margin:8px 0 4px">web3 speculation</div><div style="font-size:11px">${w3.trending_count || 0} quality-gated trending tokens${w3.top_chain ? ' · mostly ' + esc(w3.top_chain) : ''}<div class="ghost" style="font-size:10px">${(w3.top || []).map(t => esc(t[1]) + ' <span class="mute">' + esc(t[0]) + '</span>').join(' · ')}</div></div></div></div></div></div>`;
    const flash = (d.situation || {}).flash || [];
    const flashHtml = `<div class="panel"><div class="ph"><span class="t">Flash · breaking now</span><span class="meta">${flash.filter(x => x.urgency === 'alert').length} alert · ${flash.filter(x => x.urgency === 'warn').length} watch</span></div><div class="pb" style="padding:6px 14px">${flash.length ? flash.slice(0, 10).map(x => `<div style="display:flex;gap:10px;align-items:baseline;padding:4px 0;border-bottom:1px solid var(--line-soft);font-size:12px"><span class="ghost" style="width:40px;flex:none;font-size:10px">${esc(x.t)}</span><span class="chip" style="color:${urgC[x.urgency] || C.dim};border-color:${urgC[x.urgency] || C.dim};flex:none">${esc(x.category)}</span><span style="min-width:0"><b>${x.url ? `<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.headline)}</a>` : esc(x.headline)}</b> <span class="muted">${esc(x.detail || '')}</span></span></div>`).join('') : empty('nothing breaking', 'fills as moves, listings, headlines and macro prints arrive')}</div></div>`;
    const newsHtml = `<div class="panel"><div class="ph"><span class="t">World · biggest news and events</span><span class="meta">risk first · high-impact calendar</span></div><div class="pb" style="padding:6px 14px">${(ev.risk_flags || []).length ? `<div class="ghost" style="font-size:10px;margin-bottom:4px">risk flags: ${ev.risk_flags.map(esc).join(' · ')}</div>` : ''}${(ev.news || []).slice(0, 8).map(n => `<div style="padding:5px 0;border-bottom:1px solid var(--line-soft);font-size:12px"><span class="chip" style="color:${n.sentiment === 'risk' ? C.mg : n.sentiment === 'positive' ? C.gr : 'var(--text-dim)'}">${esc(n.category)}</span> ${n.url ? `<a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a>` : esc(n.title)}<div class="ghost" style="font-size:10px">${esc(n.source || '')}${n.age_h != null ? ` · ${n.age_h}h ago` : ''} · ${(n.products || []).slice(0, 3).map(esc).join(' · ')}</div></div>`).join('') || empty('no headlines loaded')}${(ev.calendar || []).length ? `<div class="lab10" style="margin:8px 0 2px">calendar · high impact</div>${ev.calendar.map(c => `<div style="font-size:11px;padding:2px 0"><span class="mute">${esc(c.date || c.when || '')}</span> ${esc(c.event || c.title || '')}${c.country ? ` <span class="ghost">${esc(c.country)}</span>` : ''}</div>`).join('')}` : ''}</div></div>`;
    const rivalCard = r => `<div class="card"><div class="nm"><span>${esc(r.name)}</span><span class="chip sev" style="color:${esc(r.color)};border-color:${esc(r.color)}">${esc(r.threat)}</span></div><div class="pi"><div class="r"><span>PRESSURE INDEX</span><span style="color:${esc(r.color)}">${r.pressureIndex}</span></div><div class="bar"><i style="width:${r.pressureIndex}%;background:${esc(r.color)}"></i></div></div><div class="mv">${esc(r.latestMove)}</div><div>${(r.tactics || []).map(t => `<span class="chip">${esc(t)}</span> `).join('')}</div><div class="foot"><span class="lab10">counter play</span><span style="color:${C.cy};text-align:right">${esc(r.counterPlay)}</span></div><div class="foot" style="border-top:0;padding-top:2px;font-size:10px;color:var(--text-ghost)"><span>${esc(r.source || '')}</span><span>vol ${r.vol_24h_usd ? money(r.vol_24h_usd) : '—'}${r.share != null ? ' · INR share ' + fmt(r.share, 1) + '%' : ''}</span></div><div style="margin-top:6px"><button class="btn sm c" data-dossier="${esc(r.id)}">Open dossier</button> <button class="btn sm" data-ask-text="Counter ${esc(r.name)} now: ${esc(r.counterPlay)}. Latest move: ${esc(r.latestMove)}. Check regime and limits, pick the SOP, run_sop dry-run, two compliant variants, no venue names.">Ask the brain</button></div></div>`;
    const rivalsHtml = `<div class="panel"><div class="ph"><span class="t">Rivals that matter</span><span class="meta">${(rv.major || []).length} tracked · ${(rv.minor || []).length} long tail <button class="btn sm ghost" id="minor-toggle" style="margin-left:6px">${S.showMinor ? 'hide' : 'show'} long tail</button></span></div><div class="pb"><div class="cards">${(rv.major || []).map(rivalCard).join('') || empty('no venues loaded yet', 'refreshes every 15 minutes')}</div>${S.showMinor ? `<div class="cards" style="margin-top:12px;opacity:.75">${(rv.minor || []).map(rivalCard).join('')}</div>` : `<div class="ghost" style="font-size:10px;margin-top:8px">long tail: ${(rv.minor || []).map(m => esc(m.name) + ' ' + m.pressureIndex).join(' · ') || '—'}</div>`}</div></div>
      <div class="cols"><div class="c3"><div class="panel"><div class="ph"><span class="t">Moves detected · 24–48h</span><span class="meta">surges · venue jumps · listing gaps</span></div><div class="pb"><div class="grid-tbl moves"><div class="h">time</div><div class="h">signal</div><div class="h">channel</div><div class="h">impact</div>${(rv.moves || []).map(m => `<div class="row" style="display:contents"><div class="r ghost">${esc(m.t)}</div><div class="r">${esc(m.what)}</div><div class="r mute">${esc(m.chan)}</div><div class="r" style="color:${esc(m.c)}">${esc(m.impact)}</div></div>`).join('') || `<div class="r" style="grid-column:1/-1">${empty('no moves above threshold', 'surges need a snapshot ≥ 45 min old')}</div>`}</div></div></div>
        <div class="panel"><div class="ph"><span class="t">Their campaigns · 48h</span><span class="meta">announcements · blogs · news · app notes</span></div><div class="pb">${(rv.campaigns || []).length ? `<div class="grid-tbl" style="grid-template-columns:80px minmax(0,1fr) 110px 80px 150px"><div class="h">venue</div><div class="h">campaign</div><div class="h">type</div><div class="h">impact</div><div class="h">our counter</div>${rv.campaigns.slice(0, 12).map(c => `<div class="row" style="display:contents"><div class="r mute">${esc(c.venue)}</div><div class="r">${c.url ? `<a href="${esc(c.url)}" target="_blank" rel="noopener">${esc(c.title)}</a>` : esc(c.title)}<div class="ghost" style="font-size:10px">${esc(c.source || '')} · ${esc(c.published_at || '')}</div></div><div class="r mute" style="font-size:10px;letter-spacing:.08em">${esc(c.type)}</div><div class="r" style="color:${c.impact === 'MATERIAL' ? C.mg : c.impact === 'WATCH' ? C.am : 'var(--text-ghost)'}">${esc(c.impact)}</div><div class="r" style="font-size:10px">${c.counter_sop ? `<a href="#" data-ask-text="Counter this competitor campaign (${esc(c.venue)}: ${esc(c.title)}) with ${esc(c.counter_sop)}: check regime and limits, run_sop dry-run, two compliant variants, no venue names. ${esc(c.counter)}">${esc(c.counter_sop.replace('sop_', ''))}</a>` : '<span class="ghost">product / monitor</span>'}</div></div>`).join('')}</div>` : empty('no competitor campaigns detected in 48h', 'sources refresh every 15 minutes')}</div></div></div>
      <div class="c1"><div class="panel"><div class="ph"><span class="t">Share of INR spot</span><span class="meta">tracked venues</span></div><div class="pb sov">${(rv.sov || []).map(s => `<div class="r"><span>${esc(s.name)}</span><span style="color:${esc(s.c)}">${fmt(s.pct, 1)}%</span></div><div class="bar"><i style="width:${Math.min(100, s.pct || 0)}%;background:${esc(s.c)}"></i></div>`).join('') || empty('no share data')}</div></div>
        <div class="panel"><div class="ph"><span class="t">Counter actions</span><span class="meta">owner · sop</span></div><div class="pb">${(rv.actions || []).slice(0, 6).map(a => `<div style="padding:6px 0;border-bottom:1px solid var(--line-soft);font-size:12px"><span class="chip" style="color:${a.priority >= 80 ? C.mg : a.priority >= 60 ? C.am : C.dim}">${esc(a.type)}</span> <b>${esc(a.symbol)}</b> <span class="mute">${esc(a.owner)}</span><div class="muted" style="font-size:11px;margin-top:3px">${esc(a.what)}</div>${a.sop ? `<div class="ghost" style="font-size:10px">${esc(a.sop)} · <a href="#" data-ask-text="Act on competitive action ${esc(a.type)} for ${esc(a.symbol)}: ${esc(a.what)}. Use ${esc(a.sop)} via run_sop dry-run then real; no venue names in copy.">ask the brain</a></div>` : ''}</div>`).join('') || empty('no actions')}</div></div>
        <div class="panel"><div class="ph"><span class="t">App Store · finance (IN)</span><span class="meta">rank · rating</span></div><div class="pb">${Object.keys(rv.apps || {}).length ? Object.entries(rv.apps).sort((a, b) => (a[1].rank_top_free || 999) - (b[1].rank_top_free || 999)).map(([k, a]) => `<div style="display:flex;justify-content:space-between;gap:8px;padding:5px 0;border-bottom:1px solid var(--line-soft);font-size:12px"><span style="color:${k === 'coindcx' ? C.cy : 'var(--text)'}">${esc(a.name)}<div class="ghost" style="font-size:10px">v${esc(a.version || '—')} · ${esc(a.updated || '')}${a.rank_top_free_7d_ago ? ` · was #${a.rank_top_free_7d_ago}` : ''}</div></span><span style="text-align:right"><span class="mono">${a.rank_top_free ? '#' + a.rank_top_free : '—'}</span><div class="ghost" style="font-size:10px">★ ${fmt(a.rating, 2)} · ${fmt(a.ratings_count, 0)}</div></span></div>`).join('') : empty('no app data')}</div></div></div></div>`;
    const to = mk.top_oi || {};
    const oiHtml = `<div class="panel"><div class="ph"><span class="t">Top open interest</span><span class="meta">reference venue · HL share when cached</span></div><div class="pb" style="padding:6px 14px"><div class="grid-tbl" style="grid-template-columns:56px 90px 60px 70px 70px 90px"><div class="h">asset</div><div class="h">OI</div><div class="h">24h</div><div class="h">fund APR</div><div class="h">HL share</div><div class="h">cheapest longs</div>${(to.crypto || []).map(r => `<div class="row" style="display:contents"><div class="r"><b>${esc(r.symbol)}</b></div><div class="r">${money(r.oi_usd)}</div><div class="r ${cls(r.chg_24h)}">${pct(r.chg_24h)}</div><div class="r mute">${r.funding_apr_pct != null ? fmt(r.funding_apr_pct, 0) + '%' : '—'}</div><div class="r" style="color:${C.cy}">${r.hl_oi_share_pct != null ? r.hl_oi_share_pct + '%' : '—'}</div><div class="r mute">${esc(r.cheapest_for_longs || '—')}</div></div>`).join('')}</div>${(to.tokenised || []).length ? `<div class="lab10" style="margin:10px 0 4px">tokenised · top OI</div>${to.tokenised.map(r => `<span class="chip">${esc(r.symbol)} ${money(r.oi_usd)} <span class="${cls(r.chg_24h)}">${pct(r.chg_24h)}</span></span> `).join('')}` : ''}</div></div>`;
    const bc = mk.by_category || {}; const cats = Object.keys(bc); const cat = bc[S.mkCat] ? S.mkCat : cats[0]; const cur = bc[cat] || {};
    const rowsOf = (arr) => (arr || []).map(r => `<div style="display:flex;justify-content:space-between;gap:8px;font-size:12px;padding:3px 0;border-bottom:1px solid var(--line-soft)"><span><b>${esc(r.symbol)}</b>${r.chain ? ` <span class="ghost">${esc(r.chain)}</span>` : ''}</span><span>${r.price != null ? fmt(r.price, r.price < 1 ? 4 : 2) + ' · ' : ''}<span class="${cls(r.chg_24h)}">${pct(r.chg_24h)}</span> <span class="ghost">${money(r.vol_24h_usd)}</span></span></div>`).join('') || '<div class="ghost" style="font-size:11px">—</div>';
    const catHtml = `<div class="panel"><div class="ph"><span class="t">Top assets · by category</span><span class="meta" id="mk-cat-tabs">${cats.map(k => `<button class="f ${k === cat ? 'on' : ''}" data-mkcat="${k}" style="margin-left:4px">${k.replace('_', ' ').toUpperCase()}</button>`).join('')}</span></div><div class="pb"><div class="cols">${Object.entries(cur).map(([k, arr]) => `<div class="c1"><div class="lab10" style="margin-bottom:4px">${esc(k.replace('_', ' '))}</div>${rowsOf(arr)}</div>`).join('')}</div></div></div>`;
    const prodHtml = `<div class="panel"><div class="ph"><span class="t">Intel by product</span><span class="meta">what today means for each CoinDCX product · queue a campaign on any alert</span></div><div class="pb"><div class="cards">${(mk.by_product || []).map(p => `<div class="card"><div class="nm"><span>${esc(p.name)}</span><span class="chip sev" style="color:${p.status === 'act' ? C.mg : p.status === 'watch' ? C.am : 'var(--text-ghost)'};border-color:${p.status === 'act' ? C.mg : p.status === 'watch' ? C.am : 'var(--line)'}">${esc(p.status)}</span></div><div class="mv">${esc(p.lens)}</div>${(p.global_alerts || []).length ? `<div class="ghost" style="font-size:10px;margin-bottom:4px">global: ${p.global_alerts.map(g => esc(g.headline)).join(' · ')}</div>` : ''}${(p.facts || []).map(x => `<div style="font-size:11px;padding:3px 0;border-bottom:1px solid var(--line-soft)"><span style="color:${urgC[x.urgency] || C.dim}">▸</span> <b>${esc(x.headline)}</b> <span class="ghost">${esc(x.detail || '')}</span><div style="margin-top:2px;display:flex;gap:6px;flex-wrap:wrap"><button class="btn sm c" data-alert-campaign="1" data-product="${esc(p.product)}" data-headline="${esc(x.headline)}" data-detail="${esc(x.detail || '')}" data-sop="${esc((x.campaign || {}).sop || '')}">Queue campaign · ${esc(((x.campaign || {}).sop || '').replace('sop_', ''))}</button><button class="btn sm" data-ask-text="Create a campaign now for product ${esc(p.product)} from this alert: ${esc(x.headline)} — ${esc(x.detail || '')}. Use campaign_from_alert(dry_run=true) with SOP ${esc((x.campaign || {}).sop || '')}, then write two better compliant variants (fact + tool, no venue names, no direction) and queue it; respect regime, limits and the never-list (${esc((p.never || []).join(', '))}).">Ask the brain to write it</button></div></div>`).join('') || '<div class="ghost" style="font-size:11px">quiet</div>'}${(p.hooks || []).length ? `<div class="lab10" style="margin:8px 0 2px">hooks</div>${p.hooks.map(h => `<div style="font-size:11px">${esc(h.trigger)} <a href="#" class="ghost" style="font-size:10px" data-ask-text="Act on hook ${esc(h.id)} for product ${esc(p.product)}: ${esc(h.trigger)}. Use ${esc(h.sop || 'the matching SOP')} via run_sop dry-run then real; respect regime, limits and the product never-list (${esc((p.never || []).join(', '))}).">ask the brain</a></div>`).join('')}` : ''}<div class="foot"><span class="lab10">sops</span><span style="text-align:right;font-size:10px">${(p.sops || []).map(x => esc(x.replace('sop_', ''))).join(' · ') || '—'}</span></div></div>`).join('')}</div></div></div>`;
    const hooksHtml = `<div class="panel"><div class="ph"><span class="t">Compiled campaign hooks</span><span class="meta">regime ${esc(mk.regime || '—')} · ${(mk.hooks || []).length} allowed</span></div><div class="pb"><div class="grid-tbl hooks"><div class="h">angle</div><div class="h">hook</div><div class="h">cohort</div>${(mk.hooks || []).map(h => `<div class="row" style="display:contents"><div class="r" style="color:${esc(h.c)};font-size:10px;letter-spacing:.12em">${esc(h.regime)}</div><div class="r">${esc(h.hook)} <a href="#" data-ask-text="Act on hook ${esc(h.id)}: ${esc(h.hook)}. Use SOP ${esc(h.sop || 'sop_asset_spotlight')} via run_sop dry-run then real, two compliant variants, respect regime policy and limits." class="ghost" style="font-size:10px">ask the brain</a></div><div class="r mute">${esc(h.cohort)}</div></div>`).join('') || `<div class="r" style="grid-column:1/-1">${empty('no allowed hooks', 'angle policy blocks everything in this regime')}</div>`}</div></div></div>`;
    const tilesHtml = `<div class="tiles">${(mk.tiles || []).map(t => `<div class="mtile"><div class="sy"><span>${esc(t.symbol)}</span><span class="${t.change == null ? 'mute' : cls(t.change)}">${t.change == null ? '' : pct(t.change)}</span></div><div class="px">${typeof t.price === 'number' ? fmt(t.price, t.price < 1 ? 4 : 2) : esc(t.price ?? '—')}</div><div class="nt">${esc(t.note || '')}</div></div>`).join('')}</div>`;
    const t0 = (d.situation || {}).tier0;
    body.innerHTML = `${t0 ? `<div class="err" style="border-color:${C.mg};margin-bottom:12px">tier-0 · ${esc(String(t0.kind || '').replace(/_/g, ' '))} · ${esc(t0.detail)} · promotions frozen; global announcement sop with product lenses is the response <button class="btn sm m" data-ask-text="Tier-0 event: ${esc(t0.detail)}. announcement_lenses → core fact + product lenses → run_sop('sop_global_announcement_lenses') dry-run then real.">hand to the brain</button></div>` : ''}
      <div class="lab-nav">${[['reads', 'BEHAVIOUR'], ['recs', 'RECOMMENDATIONS'], ['flow', 'MONEY FLOW'], ['world', 'WORLD'], ['rivals', 'RIVALS'], ['markets', 'MARKETS'], ['bench', 'BENCHMARKS'], ['ocx', 'ON-CHAIN VS CEX']].map(([k, l]) => `<a href="#lab" data-jump="${k}">${l}</a>`).join('')}</div>
      <div class="cols" id="lab-reads"><div class="c3">${readsHtml}</div><div class="c1">${gauge}</div></div>
      <div id="lab-recs">${recsHtml}</div>
      <div id="lab-flow">${flowHtml}</div>
      <div class="cols" id="lab-world"><div class="c2">${flashHtml}</div><div class="c2">${newsHtml}</div></div>
      <div id="lab-rivals">${rivalsHtml}</div>
      <div id="lab-markets"><div class="cols"><div class="c2">${oiHtml}</div><div class="c2">${catHtml}</div></div>${prodHtml}${tilesHtml}${hooksHtml}</div>
      <div class="panel" id="bench"><div class="ph"><span class="t">Best in industry · by category</span><span class="meta" id="bench-tabs"></span></div><div class="pb" id="bench-body"><div class="loading"><div class="dash"></div></div></div></div>
      <div class="panel" id="ocx"><div class="ph"><span class="t">Hyperliquid vs centralised · on-chain landscape</span><span class="meta">our liquidity venue · free sources</span></div><div class="pb" id="ocx-body"><div class="loading"><div class="dash"></div></div></div></div>
      <div class="ghost" style="font-size:10px;margin-top:4px">${esc(d.note || '')} · ${esc(mk.narrative || '')}</div>`;
    renderBench(); renderOcx();
    const mt = $('#minor-toggle'); if (mt) mt.onclick = () => { S.showMinor = !S.showMinor; views.lab(); };
  } catch (e) { body.innerHTML = err(e.message); }
};

S.benchCat = S.benchCat || 'perps';
async function openDossier(venue) {
  const money = (v) => v == null ? '—' : v >= 1e9 ? '$' + fmt(v / 1e9, 2) + 'B' : v >= 1e6 ? '$' + fmt(v / 1e6, 1) + 'M' : '$' + fmt(v, 0);
  let host = $('#dossier'); if (!host) { host = document.createElement('div'); host.id = 'dossier'; const anchor = $('#lab-rivals') || $('#body .cards'); (anchor ? anchor.parentNode : $('#body')).insertBefore(host, anchor || null); }
  host.innerHTML = `<div class="panel"><div class="ph"><span class="t">Dossier · ${esc(venue)}</span></div><div class="loading"><div class="dash"></div></div></div>`;
  try {
    const d = await api(`/api/market/competitor/${encodeURIComponent(venue)}`);
    const m = d.market || {}; const a = d.app || {}; const c7 = d.campaigns_7d || {}; const pr = d.pressure || {};
    host.innerHTML = `<div class="panel"><div class="ph"><span class="t">Dossier · ${esc(d.name)}</span><span class="meta">${esc(d.scope)} · ${(d.categories || []).map(esc).join(' · ')} · <button class="btn sm ghost" id="dossier-close">close</button></span></div><div class="pb">
      <div class="strip" style="margin-bottom:12px"><div class="tile"><div class="k">PRESSURE</div><div class="v" style="color:${esc(pr.color || C.txt)}">${pr.index ?? '—'}</div><div class="s">${esc(pr.threat || '—')}</div></div><div class="tile"><div class="k">PLAYBOOK (7D)</div><div class="v" style="font-size:16px">${esc(d.playbook)}</div><div class="s">${c7.count || 0} campaigns · ${c7.cadence_per_day || 0}/day</div></div><div class="tile"><div class="k">VOLUME (CMC)</div><div class="v">${money(m.cmc_total_vol_24h_usd)}</div><div class="s">${m.cmc_vol_chg_24h_pct != null ? pct(m.cmc_vol_chg_24h_pct, 0) + ' 24h · ' : ''}${m.cmc_vol_chg_7d_pct != null ? pct(m.cmc_vol_chg_7d_pct, 0) + ' 7d' : ''}${m.share_of_tracked_inr_spot_pct != null ? ' · INR share ' + m.share_of_tracked_inr_spot_pct + '%' : ''}</div></div><div class="tile"><div class="k">FEES · TRAFFIC</div><div class="v" style="font-size:16px">${m.taker_fee_pct != null ? 'taker ' + m.taker_fee_pct + '%' : '—'}</div><div class="s">${m.weekly_visits ? fmt(m.weekly_visits, 0) + ' visits/wk' : ''}${m.cmc_score ? ' · score ' + m.cmc_score : ''}</div></div><div class="tile"><div class="k">APP STORE (IN)</div><div class="v" style="font-size:16px">${a.rank_top_free ? '#' + a.rank_top_free : '—'}</div><div class="s">${a.rating ? '★ ' + fmt(a.rating, 2) + ' · ' + fmt(a.ratings_count, 0) : ''}${a.version ? ' · v' + esc(a.version) : ''}${a.rank_7d_ago ? ' · was #' + a.rank_7d_ago : ''}</div></div></div>
      <div class="cols"><div class="c2"><div class="lab10" style="margin-bottom:4px">campaigns · last 7 days</div>${Object.entries(c7.by_type || {}).map(([k, v]) => `<span class="chip">${esc(k)} ${v}</span> `).join('') || '<span class="ghost">none detected</span>'}<div class="ghost" style="font-size:10px;margin:4px 0 8px">channels: ${Object.entries(c7.channels || {}).map(([k, v]) => esc(k) + ' ' + v).join(' · ') || '—'} · audience: ${Object.entries(c7.audience_focus || {}).map(([k, v]) => esc(k) + ' ' + v).join(' · ') || '—'}</div>${(c7.latest || []).map(x => `<div style="font-size:11px;padding:3px 0;border-bottom:1px solid var(--line-soft)"><span class="mute">${esc(x.type)}</span> ${x.url ? `<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title)}</a>` : esc(x.title)} <span class="ghost">${esc(x.published_at || '')}</span></div>`).join('')}</div>
      <div class="c1"><div class="lab10" style="margin-bottom:4px">position by category</div>${Object.entries(m.by_category || {}).map(([k, v]) => `<div style="font-size:11px;padding:3px 0;border-bottom:1px solid var(--line-soft)"><b>${esc(k)}</b> · rank #${v.rank} · ${money(v.vol_24h_usd)}${v.oi_usd ? ' · OI ' + money(v.oi_usd) : ''}<div class="ghost" style="font-size:10px">leader ${esc(v.leader || '—')} · top ${(v.top_pairs || []).slice(0, 4).map(p => esc(p.symbol)).join(', ')}</div></div>`).join('') || '<span class="ghost">no category data</span>'}
        <div class="lab10" style="margin:10px 0 4px">what changed · 7d</div>${(d.what_changed_7d || []).map(x => `<div style="font-size:11px">▸ ${esc(x)}</div>`).join('') || '<span class="ghost" style="font-size:11px">history builds daily</span>'}
        <div class="lab10" style="margin:10px 0 4px">moves</div>${[...(d.moves.surges || []).map(x => `<div style="font-size:11px">surge ${esc(x.symbol)} +${x.surge_pct}%</div>`), ...(d.moves.listing_gaps || []).map(x => `<div style="font-size:11px">lists ${esc(x.symbol)} (${esc(x.product)}) we don't</div>`)].join('') || '<span class="ghost" style="font-size:11px">none</span>'}</div></div>
      <div class="lab10" style="margin:12px 0 4px">how we beat them</div>${(d.how_to_beat || []).map(x => `<div style="font-size:12px;padding:3px 0">▸ ${esc(x)}</div>`).join('')}
      <div class="lab10" style="margin:10px 0 4px">counters</div>${(d.counters || []).map(x => `<div style="font-size:11px">${esc(x.against)} → <b>${esc(x.sop || 'product / monitor')}</b> <span class="muted">${esc(x.how)}</span>${x.sop ? ` <a href="#" class="ghost" style="font-size:10px" data-ask-text="Counter ${esc(d.name)}'s ${esc(x.against)} play with ${esc(x.sop)}: check regime and limits, run_sop dry-run, two compliant variants, no venue names. ${esc(x.how)}">ask the brain</a>` : ''}</div>`).join('')}
      <div class="ghost" style="font-size:10px;margin-top:8px">free public sources · internal only · never named in copy</div></div></div>`;
    $('#dossier-close').onclick = () => host.remove(); host.scrollIntoView({behavior: 'smooth', block: 'start'});
  } catch (e) { host.innerHTML = err(e.message); }
}
async function renderOcx() {
  const money = (v) => v == null ? '—' : v >= 1e9 ? '$' + fmt(v / 1e9, 2) + 'B' : v >= 1e6 ? '$' + fmt(v / 1e6, 1) + 'M' : '$' + fmt(v, 0);
  try {
    const d = await api('/api/market/onchain-vs-cex'); const hl = d.hyperliquid || {}; const v = d.hl_vs_cex || {};
    $('#ocx-body').innerHTML = `<div class="strip" style="margin-bottom:12px"><div class="tile"><div class="k">HL DAILY VOLUME</div><div class="v" style="color:${C.cy}">${money(hl.daily_volume_usd)}</div><div class="s">rank #${v.rank_if_listed_with_cex ?? '—'} among tracked CEX · ${v.share_of_cex_top5_volume_pct ?? '—'}% of top-5+HL</div></div><div class="tile"><div class="k">HL OPEN INTEREST</div><div class="v">${money(hl.oi_usd)}</div><div class="s">${v.leader ? esc(v.leader) + ' volume ' + v.vs_leader_volume_x + '× HL' : '—'}${v.hl_oi_vs_binance_oi_x ? ' · Binance OI ' + v.hl_oi_vs_binance_oi_x + '×' : ''}</div></div><div class="tile"><div class="k">HL USERS</div><div class="v">${fmt(hl.users, 0)}</div><div class="s">all time (venue)</div></div><div class="tile"><div class="k">ON-CHAIN OI</div><div class="v" style="color:${C.gr}">${money((d.onchain || {}).total_onchain_oi_usd)}</div><div class="s">HL share ${(((d.onchain || {}).protocols || []).find(p => /hyperliquid perps/i.test(p.name)) || {}).share_of_onchain_pct ?? '—'}%</div></div><div class="tile"><div class="k">COINGLASS</div><div class="v" style="color:${(d.coinglass || {}).configured ? C.gr : 'var(--text-ghost)'}">${(d.coinglass || {}).configured ? 'on' : 'no key'}</div><div class="s">${(d.coinglass || {}).configured ? 'cross-venue OI/funding/liq' : 'optional free key'}</div></div></div>
      <div class="cols"><div class="c2"><div class="lab10" style="margin-bottom:6px">per coin · OI share and funding per hour</div><div class="grid-tbl" style="grid-template-columns:50px 70px 80px 80px 80px 90px"><div class="h">coin</div><div class="h">HL OI %</div><div class="h">HL fund</div><div class="h">Binance</div><div class="h">Bybit</div><div class="h">cheapest longs</div>${(d.per_coin || []).map(c => `<div class="row" style="display:contents"><div class="r"><b>${esc(c.coin)}</b></div><div class="r" style="color:${C.cy}">${c.hl_oi_share_pct}%</div><div class="r">${c.funding_1h_pct.hyperliquid ?? '—'}</div><div class="r mute">${c.funding_1h_pct.binance ?? '—'}</div><div class="r mute">${c.funding_1h_pct.bybit ?? '—'}</div><div class="r" style="color:${c.cheapest_for_longs === 'hyperliquid' ? C.gr : 'var(--text-dim)'}">${esc(c.cheapest_for_longs || '—')}</div></div>`).join('')}</div></div>
      <div class="c1"><div class="lab10" style="margin-bottom:6px">on-chain perps · open interest</div>${((d.onchain || {}).protocols || []).slice(0, 8).map(p => `<div style="display:flex;justify-content:space-between;font-size:11px;padding:3px 0;border-bottom:1px solid var(--line-soft)"><span style="color:${p.hl_ecosystem ? C.cy : 'var(--text)'}">${esc(p.name)}</span><span>${money(p.oi_usd)} <span class="ghost">${p.share_of_onchain_pct}%</span></span></div>`).join('')}<div class="lab10" style="margin:10px 0 6px">centralised · derivatives 24h</div>${(d.cex || []).slice(0, 6).map(c => `<div style="display:flex;justify-content:space-between;font-size:11px;padding:3px 0;border-bottom:1px solid var(--line-soft)"><span>${esc(c.name)}</span><span>${money(c.vol_24h_usd)} <span class="ghost">OI ${money(c.oi_usd)}</span></span></div>`).join('')}</div></div>
      <div class="ghost" style="font-size:10px;margin-top:8px">${esc(d.note || '')}</div>`;
  } catch (e) { const el = $('#ocx-body'); if (el) el.innerHTML = err(e.message); }
}
async function renderBench() {
  const money = (v) => v == null ? '—' : v >= 1e9 ? '$' + fmt(v / 1e9, 2) + 'B' : v >= 1e6 ? '$' + fmt(v / 1e6, 1) + 'M' : '$' + fmt(v, 0);
  try {
    if (!S.bench) S.bench = await api('/api/market/benchmarks');
    const cats = Object.keys(S.bench.categories || {}); const cat = S.bench.categories[S.benchCat] ? S.benchCat : cats[0]; const c = S.bench.categories[cat] || {};
    $('#bench-tabs').innerHTML = cats.map(k => `<button class="f ${k === cat ? 'on' : ''}" data-bench="${k}" style="margin-left:4px">${k.replace('_', ' / ').toUpperCase()}</button>`).join('');
    const ours = c.ours || {};
    $('#bench-body').innerHTML = `<div class="strip" style="margin-bottom:12px"><div class="tile"><div class="k">GLOBAL LEADER</div><div class="v" style="color:${C.txt}">${esc((c.leader || {}).name || '—')}</div><div class="s">${money((c.leader || {}).vol_24h_usd)} / 24h</div></div><div class="tile"><div class="k">INDIA LEADER</div><div class="v" style="color:${C.am}">${esc((c.india_leader || {}).name || '—')}</div><div class="s">${money((c.india_leader || {}).vol_24h_usd)} / 24h</div></div><div class="tile"><div class="k">OURS</div><div class="v" style="color:${C.cy}">${ours.unknown ? 'unknown' : money(ours.vol_24h_usd)}</div><div class="s">${esc(ours.source || '')}</div></div><div class="tile"><div class="k">GAP · INDIA / GLOBAL</div><div class="v" style="color:${C.mg}">${c.gap_to_india_leader_x ? c.gap_to_india_leader_x + '×' : '—'} / ${c.gap_to_leader_x ? c.gap_to_leader_x + '×' : '—'}</div><div class="s">share of top-5 ${c.our_share_of_top5_pct ?? '—'}%</div></div></div>
      <div class="grid-tbl" style="grid-template-columns:minmax(0,1.4fr) 60px 90px 90px 70px 70px minmax(0,1.6fr)"><div class="h">venue</div><div class="h">scope</div><div class="h">24h vol</div><div class="h">open int.</div><div class="h">mkts</div><div class="h">taker</div><div class="h">top pairs</div>${(c.venues || []).slice(0, 14).map(v => `<div class="row" style="display:contents"><div class="r ${v.us ? '' : ''}" style="color:${v.us ? C.cy : v.reference ? 'var(--text-ghost)' : 'var(--text)'}">${esc(v.name)}${v.reference ? ' <span class="ghost">(ref)</span>' : ''}</div><div class="r mute">${esc(v.scope)}</div><div class="r">${v.unknown ? '—' : money(v.vol_24h_usd)}</div><div class="r">${money(v.oi_usd)}</div><div class="r mute">${v.markets ?? '—'}</div><div class="r mute">${v.taker_fee_pct != null ? v.taker_fee_pct + '%' : '—'}</div><div class="r ghost" style="font-size:10px">${(v.top_pairs || []).slice(0, 4).map(p => esc(p.symbol) + ' ' + money(p.vol_24h_usd)).join(' · ') || '—'}</div></div>`).join('')}</div>
      <div class="lab10" style="margin:12px 0 6px">match their numbers</div>${(c.targets || []).length ? c.targets.map(t => t.pair ? `<div style="font-size:12px;padding:4px 0;border-bottom:1px solid var(--line-soft)"><b>${esc(t.pair)}</b> <span class="mute">vs ${esc(t.leader)}</span> · them ${money(t.their_vol_24h_usd)} · us ${money(t.our_vol_24h_usd)} · ${t.multiple ? `<span class="down">${t.multiple}×</span>` : `<span class="down">${esc(t.note || '')}</span>`}${t.sop ? ` <a href="#" class="ghost" style="font-size:10px" data-ask-text="Close the gap on ${esc(t.pair)} (${esc(t.leader)} does ${money(t.their_vol_24h_usd)}/24h vs our ${money(t.our_vol_24h_usd)}): pair_battle, then run_sop('${esc(t.sop)}') for our ${esc(t.pair)} watchers/holders; product asks if liquidity is the constraint. No venue names in copy.">ask the brain</a>` : ''}</div>` : `<div style="font-size:12px;padding:4px 0;border-bottom:1px solid var(--line-soft)"><b>${esc(t.to_match)}</b> · them ${money(t.their_vol_24h_usd)} · us ${money(t.our_vol_24h_usd)} · ${t.multiple ? t.multiple + '×' : '—'} · need +${money(t.daily_volume_needed_usd)}/day${t.step_25pct_usd ? ` (first step to 25%: +${money(t.step_25pct_usd)})` : ''}</div>`).join('') : '<div class="ghost" style="font-size:11px">no comparable figure for us in this category yet</div>'}
      <div class="ghost" style="font-size:10px;margin-top:8px">${esc(S.bench.note || '')}</div>`;
    $('#bench-tabs').onclick = e => { const b = e.target.closest('[data-bench]'); if (!b) return; S.benchCat = b.dataset.bench; renderBench(); };
  } catch (e) { const el = $('#bench-body'); if (el) el.innerHTML = err(e.message); }
}

views.ideas = async () => {
  const body = $('#body'); const filters = ['all', 'structural', 'audience', 'counter', 'sop', 'market', 'cadence'];
  body.innerHTML = `<div class="filters">${filters.map(f => `<button class="f ${S.filter === f ? 'on' : ''}" data-f="${f}">${f.toUpperCase()}</button>`).join('')}</div><div id="idea-grid">${loading()}</div>`;
  try {
    const d = await api(`/api/brain/ideas?filter=${encodeURIComponent(S.filter)}`);
    $('#idea-grid').innerHTML = (d.ideas || []).length ? `<div class="ideas">${d.ideas.map(i => `<div class="card idea ${i.structural ? 'p0' : ''}"><div class="tt">${i.structural ? '<span class="chip sev" style="color:#ff5c9e;border-color:#ff5c9e;margin-right:6px">P0</span>' : ''}${esc(i.title)}<span class="id">${esc(i.id)}</span></div>${i.tagline ? `<div class="tagline">${esc(i.tagline)}</div>` : ''}<div style="margin:6px 0">${(i.tags || []).map(t => `<span class="tag">${esc(t)}</span>`).join('')}${i.ice ? `<span class="ice" title="impact × confidence × ease">ICE ${i.ice.score} <span class="ghost">${i.ice.impact}·${i.ice.confidence}·${i.ice.ease}</span></span>` : ''}</div><div class="hyp">${esc(i.hypothesis)}</div>${i.how ? `<div class="muted" style="font-size:11px">${esc(i.how)}</div>` : ''}
      <div class="metrics"><div class="m"><div class="k">EXPECTED</div><div class="v up">${esc(i.projectedLift)}</div></div><div class="m"><div class="k">CONFIDENCE</div><div class="v" style="color:${C.cy}">${esc(i.confidence)}</div></div><div class="m"><div class="k">EFFORT</div><div class="v" style="color:${C.am}">${esc(i.effort)}</div></div></div>
      <div class="src">source · ${esc(i.sourceSignal)}</div><div class="ac" style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn sm c" data-promote="${esc(i.raw_id)}">Promote → experiment</button><button class="btn sm" data-ask-text="Improve idea ${esc(i.id)} '${esc(i.title)}': ${esc(i.hypothesis)}. Sharpen audience, KPI, holdout and copy per our skills; then record_ideas.">Ask brain to improve</button></div></div>`).join('')}</div>` : empty('no ideas for this filter', 'the feed refreshes with each cycle; expired ideas are hidden');
  } catch (e) { $('#idea-grid').innerHTML = err(e.message); }
};

views.exp = async () => {
  const body = $('#body'); body.innerHTML = loading();
  try {
    const d = await api('/api/brain/experiments');
    body.innerHTML = `<div class="kanban">${(d.columns || []).map(c => `<div class="col"><div class="ch" style="color:${esc(c.c)}"><span>${esc(c.name)}</span><span>${c.cards.length}</span></div>${c.cards.length ? c.cards.slice(0, 20).map(x => `<div class="xcard"><div class="tt">#${x.id} ${esc(x.title)}${x.ice ? ` <span class="ice">ICE ${x.ice.score}</span>` : ''}</div>${x.tagline ? `<div class="tagline">${esc(x.tagline)}</div>` : ''}<div class="nt">${esc(x.note)}</div><div class="ft"><span class="mute">${esc(x.tag)}${x.product ? ' · ' + esc(x.product) : ''}</span><span style="color:${esc(c.c)}">${esc(x.metric)}</span></div>${c.key === 'proposed' ? `<div style="display:flex;gap:6px;margin-top:6px"><button class="btn sm g" data-act="approve" data-id="proposal:${x.id}">Approve</button><button class="btn sm c" data-act="simulate" data-id="proposal:${x.id}">Simulate</button><button class="btn sm m" data-act="hold" data-id="proposal:${x.id}">Hold</button><button class="btn sm" data-ask-text="Improve experiment (proposal) #${x.id}: read proposal_detail(${x.id}) and revise_proposal with concrete changes or comment_proposal.">Improve</button></div>` : ''}</div>`).join('') : `<div class="empty" style="padding:10px 4px">empty</div>`}</div>`).join('')}</div>`;
  } catch (e) { body.innerHTML = err(e.message); }
};

views.sops = async () => {
  const body = $('#body'); body.innerHTML = loading();
  try {
    const d = await api('/api/sops'); S.sops = (d.sops || []).filter(s => s.active !== 0); if (!S.sop || !S.sops.find(s => s.id === S.sop)) S.sop = (S.sops[0] || {}).id;
    const sop = S.sops.find(s => s.id === S.sop) || {};
    const gateOf = (st) => (String(st.purpose || '').startsWith('(internal)') ? 'AUTO' : 'APPROVAL');
    body.innerHTML = `<div class="cols"><div class="c1"><div class="panel"><div class="ph"><span class="t">Library</span><span class="meta">${S.sops.length} sops</span></div><div class="soplist" style="max-height:70vh;overflow:auto">${S.sops.map(s => `<div class="it ${s.id === S.sop ? 'on' : ''}" data-sop="${esc(s.id)}"><div style="display:flex;justify-content:space-between;gap:8px"><span class="nm">${esc(s.name)}</span><span class="vv">v${s.version}</span></div><div class="fm">${esc(s.campaign_type)} · ${s.steps_count} steps · ${esc((s.audience || {}).segment_family || '')}</div></div>`).join('')}</div></div></div>
      <div class="c3"><div class="panel"><div class="ph"><span class="t">Sequence · ${esc(sop.name || '')}</span><span class="meta"><button class="btn sm c" id="sop-dry">Dry run</button> <button class="btn sm primary" id="sop-run">▷ Run → proposals</button> <button class="btn sm" data-ask-text="Run SOP '${esc(sop.id)}' on its default cohort: sop_detail, segment_study, run_sop dry_run, write two compliant variants per step, run_sop for real.">Ask brain to run it</button></span></div>
        <div class="pb"><div class="muted" style="font-size:12px;margin-bottom:8px">${esc(sop.objective || '')}${sop.user ? ` · <span class="mute">who:</span> ${esc(sop.user)}` : ''}</div>
        ${(sop.steps || []).map((st, i) => `<div class="step"><div class="n">S${i + 1}</div><div class="b"><div class="t">${esc(st.purpose)}</div><div class="d">${esc(st.copy_brief)}${st.condition ? ` · if ${esc(st.condition)}` : ''}</div><div class="m"><span style="color:${C.dim}">${esc(st.channel)}</span><span class="mute">D${st.day} · ${esc(st.send_time_ist || '')}</span><span style="color:${gateOf(st) === 'AUTO' ? C.gr : C.am}">${gateOf(st)}</span></div></div></div>`).join('')}
        <div class="rules"><div class="r"><div class="k">FREQUENCY CAP</div><div class="v">${esc(((sop.frequency || {}).max_messages_per_user_per_week ?? '—') + ' per week · ' + ((sop.frequency || {}).cadence || ''))}</div></div><div class="r"><div class="k">HOLDOUT</div><div class="v">${esc(sop.holdout_pct)}% · window ${esc(sop.measurement_window_days)}d</div></div><div class="r"><div class="k">KILL RULES</div><div class="v">${esc((sop.kill_criteria || []).join(' · '))}</div></div><div class="r"><div class="k">PRIMARY KPI</div><div class="v">${esc(sop.primary_kpi)} → ${esc(sop.target)} · guardrail ${esc(sop.guardrail_metric)}</div></div></div>
        ${(sop.ideas || []).length ? `<div class="mute" style="font-size:11px;margin-top:10px">ideas to test · ${sop.ideas.map(esc).join(' · ')}</div>` : ''}<div id="sop-out" style="margin-top:10px;font-size:12px"></div></div></div></div></div>`;
  } catch (e) { body.innerHTML = err(e.message); }
};
async function runSop(dry) {
  const out = $('#sop-out'); if (!S.sop) return;
  if (!dry && !confirm('Queue one approval-gated proposal per step? Nothing sends before approval.')) return;
  out.innerHTML = '<span class="mute">running pre-flight…</span>';
  try {
    const r = await api(`/api/sops/${encodeURIComponent(S.sop)}/run`, {method: 'POST', body: {dry_run: dry}});
    const pf = r.preflight || {};
    out.innerHTML = `<div class="${r.ok ? 'up' : 'down'}">${r.ok ? (r.run_id ? `sop/run ${esc(S.sop)} → ${r.proposal_ids.length} approval-gated proposals queued (run #${r.run_id})` : `dry run ok · nothing queued`) : esc(r.note || r.error || 'pre-flight blocked')}</div>${(pf.checks || []).map(c => `<div style="font-size:11px"><span class="${c.ok ? 'up' : 'down'}">${c.ok ? '✓' : '✗'}</span> ${esc(c.check)} <span class="mute">${esc(c.detail || '')}</span></div>`).join('')}`;
    pushTrace(r.run_id ? `sop/run ${S.sop} → ${r.proposal_ids.length} proposals` : `sop/dry-run ${S.sop} · ${r.ok ? 'ok' : 'blocked'}`, r.ok ? 'ok' : 'warn');
    if (r.run_id) refreshState();
  } catch (e) { out.innerHTML = err(e.message); }
}

views.anom = async () => {
  const body = $('#body'); body.innerHTML = loading();
  try {
    const d = await api('/api/brain/anomalies'); const rows = d.anomalies || [];
    const spark = (vals, color) => { const v = (vals || []).filter(x => x != null).map(Number); if (!v.length) return '<div class="spark"></div>'; const mx = Math.max(...v), mn = Math.min(...v); return `<div class="spark">${v.map((x, i) => `<i style="height:${Math.round(20 + (mx === mn ? 50 : (x - mn) / (mx - mn) * 80))}%;${i === v.length - 1 ? `background:${color}` : ''}"></i>`).join('')}</div>`; };
    body.innerHTML = `<div class="panel"><div class="ph"><span class="t">Deep diagnosis · ranked</span><span class="meta">vs each campaign’s own baseline · day-of-week adjusted</span></div><div class="pb">${rows.length ? rows.map(a => `<div class="an"><div><span class="chip sev" style="color:${esc(a.color)};border-color:${esc(a.color)}">${esc(a.severity)}</span> <span class="nm">${esc(a.campaign)}</span> <span class="mt">${esc(a.metric)} · baseline ${fmt(a.baseline)}${a.n_history ? ` · n=${a.n_history}` : ''}</span><div class="ca"><span class="lab10">cause ·</span> ${esc(a.cause)}</div><div class="op"><span class="lab10">option ·</span> ${esc(a.option)}</div></div>
      <div class="rt"><div class="dl" style="color:${esc(a.color)}">${esc(a.delta || '—')}</div>${spark(a.trend, a.color)}<div class="cap">14D TREND</div><button class="btn sm" style="margin-top:4px" data-ask-text="Diagnose ${esc(a.campaign)} (${esc(a.metric)} ${esc(a.delta)}): campaign_diagnosis, then propose the do-first option as a proposal if it is an action.">Ask the brain</button></div></div>`).join('') : empty('no anomalies above baseline', 'next snapshot at ' + ((((S.state || {}).bus || []).find(b => b.k === 'SCHEDULER') || {}).v || '09:00'))}</div></div>`;
  } catch (e) { body.innerHTML = err(e.message); }
};

views.atlas = async () => {
  const body = $('#body'); body.innerHTML = loading();
  try {
    const d = await api('/api/brain/atlas'); S.atlas = d;
    const pi = d.peace || {}; const pc = pi.counts || {}; const stC = {too_much: C.mg, in_band: C.gr, too_little: C.am};
    const famHtml = `<div class="panel"><div class="ph"><span class="t">Cohort families · decoded from nomenclature</span><span class="meta">${d.segments || 0} segments · ${(d.families || []).length} families · latest version first</span></div><div class="pb"><div class="grid-tbl" style="grid-template-columns:minmax(0,1.2fr) minmax(0,1.6fr) 90px 80px 70px 90px minmax(0,1fr)"><div class="h">family</div><div class="h">meaning</div><div class="h">stage</div><div class="h">reach</div><div class="h">ver</div><div class="h">click %</div><div class="h">flags · products</div>${(d.families || []).map(f => `<div class="row" style="display:contents"><div class="r"><b>${esc(f.family)}</b><div class="ghost" style="font-size:10px">${esc((f.latest || {}).name || '')}</div></div><div class="r" style="font-size:11px">${esc(f.meaning || '—')}</div><div class="r mute" style="font-size:10px;letter-spacing:.08em">${esc(f.stage || '—')}</div><div class="r">${f.reach ? fmt(f.reach, 0) : '—'}</div><div class="r mute">${esc((f.latest || {}).version || '—')}${(f.versions || []).length > 1 ? ` <span class="ghost">(${f.versions.length})</span>` : ''}</div><div class="r">${(f.performance || {}).click_rate != null ? fmt(f.performance.click_rate, 2) + '%' : '—'}${f.delta && f.delta.click_rate_pp != null ? ` <span class="${cls(f.delta.click_rate_pp)}" style="font-size:10px">${f.delta.click_rate_pp > 0 ? '+' : ''}${f.delta.click_rate_pp}pp</span>` : ''}</div><div class="r" style="font-size:10px">${(f.flags || []).map(x => `<span class="chip" style="color:${x === 'no_campaign_attached' || x === 'worse_than_previous_version' ? C.am : x === 'undefined_codes' ? C.mg : C.dim}">${esc(x.replace(/_/g, ' '))}</span>`).join(' ')} ${(f.products || []).map(esc).join(' · ')} <a href="#" class="ghost" data-ask-text="Study cohort family ${esc(f.family)} (${esc(f.meaning || '')}): segment_study, attached campaigns and their performance, the SOP that should own it, and one experiment to run this week. Respect limits and peace index.">ask the brain</a></div></div>`).join('') || `<div class="r" style="grid-column:1/-1">${empty('no segments synced yet', 'run the daily cycle or sync segments; families appear once uploads are decoded')}</div>`}</div>${(d.unknown_tokens || []).length ? `<div class="ghost" style="font-size:10px;margin-top:6px">undefined codes in names: ${d.unknown_tokens.map(([t, n]) => esc(t) + ' ×' + n).join(' · ')} · <a href="#" data-ask-text="These segment-name tokens are undefined in the nomenclature: ${esc(d.unknown_tokens.map(t => t[0]).join(', '))}. Propose meanings from context and ask the team to confirm via a data request.">define them</a></div>` : ''}</div></div>`;
    const peaceHtml = `<div class="panel"><div class="ph"><span class="t">Peace index</span><span class="meta">touches per user per week vs cap</span></div><div class="pb"><div class="strip" style="margin-bottom:10px">${['too_much', 'in_band', 'too_little'].map(k => `<div class="tile"><div class="k">${k.replace('_', ' ').toUpperCase()}</div><div class="v" style="color:${stC[k]}">${pc[k] ?? 0}</div><div class="s">families</div></div>`).join('')}</div>${(pi.families || []).filter(r => r.status !== 'in_band').slice(0, 10).map(r => `<div style="font-size:11px;padding:3px 0;border-bottom:1px solid var(--line-soft)"><span class="chip" style="color:${stC[r.status]}">${esc(r.status.replace('_', ' '))}</span> <b>${esc(r.family)}</b> <span class="mute">${esc(r.stage)}</span> · ${r.touches_per_user_week}/${r.limit_total} per wk${(r.breaches || []).length ? `<div class="ghost" style="font-size:10px">${r.breaches.map(esc).join(' · ')}</div>` : ''}</div>`).join('') || '<div class="ghost" style="font-size:11px">every family is in band</div>'}<div class="ghost" style="font-size:10px;margin-top:6px">${esc(pi.method || '')}</div></div></div>`;
    const lim = d.limits || {}; const pu = lim.per_user || {};
    const nsHtml = `<div class="panel"><div class="ph"><span class="t">North star · hard limits</span><span class="meta">regime multiplier ${pi.multiplier ?? 1}</span></div><div class="pb"><div style="font-size:12px;color:var(--text-hi)">${esc(d.north_star || '')}</div><div class="lab10" style="margin:10px 0 4px">per user · per week</div>${Object.entries(pu).map(([ch, v]) => `<span class="chip">${esc(ch)} ≤ ${v.per_week ?? '—'}${v.per_day != null ? ` (${v.per_day}/d)` : ''}</span> `).join('')}<div class="ghost" style="font-size:10px;margin-top:4px">total ≤ ${lim.total_per_week ?? '—'}/week · quiet hours ${esc(String((lim.quiet_hours || {}).start || '22:00'))}–${esc(String((lim.quiet_hours || {}).end || '08:00'))} · edit in Settings or ask the brain</div></div></div>`;
    const prodHtml = `<div class="panel"><div class="ph"><span class="t">Product cohorts · how each is treated</span><span class="meta">lens · never · cadence · cross-sell</span></div><div class="pb"><div class="cards">${(d.products || []).map(p => `<div class="card"><div class="nm"><span>${esc(p.name)}</span><span class="chip">${p.families || 0} fam · ${p.reach ? fmt(p.reach, 0) : '—'}</span></div><div class="mv">${esc(p.lens)}</div><div style="font-size:11px"><span class="lab10">never</span> ${(p.never || []).map(esc).join(' · ')}</div><div style="font-size:11px;margin-top:3px"><span class="lab10">cadence</span> ${esc(p.cadence)}</div><div class="foot"><span class="lab10">cross-sell</span><span style="text-align:right;font-size:10px">${(p.cross_sell || []).map(esc).join(' · ')}</span></div>${p.click_rate != null ? `<div class="ghost" style="font-size:10px;margin-top:4px">click ${fmt(p.click_rate, 2)}% across ${p.campaigns} campaigns</div>` : ''}</div>`).join('')}</div></div></div>`;
    const studiesHtml = `<div class="panel"><div class="ph"><span class="t">Studies to run</span><span class="meta">questions the data can answer</span></div><div class="pb">${(d.studies || []).map(s => `<div style="padding:6px 0;border-bottom:1px solid var(--line-soft)"><b style="font-size:12px">${esc(s.title)}</b><div style="font-size:11px;color:var(--text-dim)">${esc(s.question)}</div><div class="ghost" style="font-size:10px">${esc(s.method)}</div><div style="font-size:11px;margin-top:2px"><span class="lab10">if true ·</span> ${esc(s.action_if_true)} <a href="#" class="ghost" style="font-size:10px" data-ask-text="Run the study '${esc(s.title)}': ${esc(s.question)} Method: ${esc(s.method)} Report the numbers and propose the action if it holds.">ask the brain</a></div></div>`).join('') || empty('no studies suggested')}</div></div>`;
    const reqHtml = `<div class="panel"><div class="ph"><span class="t">Data the brain asked for</span><span class="meta">open requests</span></div><div class="pb">${(d.requests || []).map(r => `<div style="font-size:11px;padding:4px 0;border-bottom:1px solid var(--line-soft)"><span class="chip" style="color:${(r.priority || 0) >= 70 ? C.mg : C.am}">${esc(r.kind || 'data')}</span> <b>${esc(r.title || '')}</b> <span class="mute">${esc(r.why || '')}</span></div>`).join('') || '<div class="ghost" style="font-size:11px">nothing outstanding</div>'}</div></div>`;
    body.innerHTML = `${famHtml}<div class="cols"><div class="c2">${peaceHtml}</div><div class="c2">${nsHtml}</div></div>${prodHtml}<div class="cols"><div class="c2">${studiesHtml}</div><div class="c2">${reqHtml}</div></div>`;
  } catch (e) { body.innerHTML = err(e.message); }
};


// ── navigation / keyboard / palette ───────────────────────────────────────────
function show(id) { id = ALIAS[id] || id; if (!views[id]) id = 'brain'; S.screen = id; location.hash = id; renderChrome(); views[id]().catch(e => { $('#body').innerHTML = err(e.message); }); }
document.addEventListener('click', async e => {
  const go = e.target.closest('[data-go]'); if (go) return show(go.dataset.go);
  const act = e.target.closest('[data-act]'); if (act) { const card = act.closest('.dir'); return actDirective(act.dataset.id, act.dataset.act, card ? +card.dataset.i : 0); }
  const ask = e.target.closest('[data-ask]'); if (ask) { const d = S.directives.find(x => x.id === ask.dataset.ask); return openPalette(d ? `Directive: ${d.title}. ${d.rationale} What exactly should we do, and can you queue it?` : ''); }
  const askT = e.target.closest('[data-ask-text]'); if (askT) { e.preventDefault(); return openPalette(askT.dataset.askText); }
  const mkc = e.target.closest('[data-mkcat]'); if (mkc) { S.mkCat = mkc.dataset.mkcat; return views.lab(); }
  const jp = e.target.closest('[data-jump]'); if (jp) { e.preventDefault(); const el = $('#lab-' + jp.dataset.jump) || $('#' + jp.dataset.jump); if (el) el.scrollIntoView({behavior: 'smooth', block: 'start'}); return; }
  const ac = e.target.closest('[data-alert-campaign]'); if (ac) { if (!confirm(`Queue approval-gated proposals via ${ac.dataset.sop || 'the product SOP'}? Copy is a compliant placeholder you can edit in Experiments.`)) return; ac.disabled = true; try { const r = await api('/api/market/alert-campaign', {method: 'POST', body: {product: ac.dataset.product, headline: ac.dataset.headline, detail: ac.dataset.detail, sop_id: ac.dataset.sop || null}}); if (r.ok && r.run_id) { toast(`run #${r.run_id}: ${r.proposal_ids.length} proposal(s) queued → Experiments`, 'ok', 7000); pushTrace(`market/alert-campaign ${ac.dataset.product} → ${r.proposal_ids.length} proposals`, 'ok'); refreshState(); } else { toast(r.note || r.error || 'pre-flight blocked: ' + ((r.preflight || {}).checks || []).filter(c => !c.ok).map(c => c.check + ' ' + (c.detail || '')).join('; '), 'warn', 9000); pushTrace(`market/alert-campaign blocked · ${ac.dataset.product}`, 'warn'); } } catch (err2) { toast(err2.message); } finally { ac.disabled = false; } return; }
  const dsr = e.target.closest('[data-dossier]'); if (dsr) { e.preventDefault(); return openDossier(dsr.dataset.dossier); }
  const f = e.target.closest('[data-f]'); if (f) { S.filter = f.dataset.f; return views.ideas(); }
  const sop = e.target.closest('[data-sop]'); if (sop) { S.sop = sop.dataset.sop; return views.sops(); }
  const pr = e.target.closest('[data-promote]'); if (pr) { try { const r = await api(`/api/brain/ideas/${encodeURIComponent(pr.dataset.promote)}/promote`, {method: 'POST', body: {}}); pushTrace(r.trace, 'info'); openPalette(r.agent_prompt || ''); } catch (err2) { toast(err2.message); } return; }
  if (e.target.closest('#sop-dry')) return runSop(true); if (e.target.closest('#sop-run')) return runSop(false);
  if (e.target.closest('#scan-toggle')) { e.preventDefault(); S.scan = !S.scan; document.body.classList.toggle('noscan', !S.scan); try { localStorage.setItem('moe.scan', S.scan ? 'on' : 'off'); } catch (_) {} renderChrome(); return; }
  if (e.target.closest('#cmd')) return openPalette('');
  if (e.target.closest('#auto')) { const on = !((S.state || {}).autopilot); try { await api('/api/engine/setting', {method: 'POST', body: {key: 'autopilot_enabled', value: on}}); pushTrace(on ? 'autopilot armed · approval still required for sends' : 'autopilot disarmed', on ? 'ok' : 'warn'); await refreshState(); } catch (err2) { toast(err2.message); } return; }
  if (e.target.closest('#cycle')) { const b = $('#cycle'); b.disabled = true; pushTrace('cycle/start mode=guarded', 'info'); try { const r = await api('/api/brain/cycle/run', {method: 'POST', body: {}}); pushTrace(`cycle/done · ${(r.steps || []).join(' → ') || r.status || 'ok'}`, 'ok'); await refreshState(); show(S.screen); } catch (err2) { toast(err2.message); pushTrace('cycle/failed · ' + err2.message, 'alert'); } finally { b.disabled = false; } return; }
  if (e.target.closest('#palette') && !e.target.closest('.pal')) closePalette();
});
function openPalette(text) { const p = $('#palette'); p.hidden = false; const i = $('#pal-in'); i.value = text || ''; i.focus(); const m = ((S.state || {}).bus || []).find(b => b.k === 'BRAIN'); $('#pal-model').textContent = m ? m.v : ''; }
function closePalette() { $('#palette').hidden = true; }
async function sendPalette() {
  const i = $('#pal-in'); const q = i.value.trim(); if (!q || S.busy) return; S.busy = true; const out = $('#pal-out');
  out.innerHTML += `<div class="who">YOU</div><div>${esc(q)}</div><div class="who">BRAIN</div><div id="pal-wait" class="mute">thinking · tools run locally · writes queue for approval <span class="cursor"></span></div>`; out.scrollTop = out.scrollHeight; i.value = '';
  pushTrace(`brain/ask "${q.slice(0, 60)}"`, 'info');
  try { const r = await api('/api/brain/ask', {method: 'POST', body: {message: q}}); $('#pal-wait').outerHTML = md(r.reply || '') + ((r.tool_used || []).length ? `<div class="ghost" style="font-size:10px">tools · ${r.tool_used.map(esc).join(' · ')}${r.model ? ' · ' + esc(r.model) : ''}</div>` : ''); pushTrace(`brain/answer · ${(r.tool_used || []).length} tools`, 'ok'); refreshState(); }
  catch (e) { $('#pal-wait').outerHTML = err(e.message); pushTrace('brain/ask failed · ' + e.message, 'alert'); }
  finally { S.busy = false; out.scrollTop = out.scrollHeight; }
}
$('#pal-in').addEventListener('keydown', e => { if (e.key === 'Enter') { e.preventDefault(); sendPalette(); } });
document.addEventListener('keydown', e => {
  const typing = ['INPUT', 'TEXTAREA'].includes((e.target || {}).tagName);
  if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); return $('#palette').hidden ? openPalette('') : closePalette(); }
  if (e.key === 'Escape') return closePalette();
  if (typing) return;
  if (/^[1-7]$/.test(e.key)) return show(NAV[+e.key - 1].id);
  if (e.key === 'a' && S.screen === 'brain' && S.directives[S.focus] && S.directives[S.focus].actions.includes('approve')) return actDirective(S.directives[S.focus].id, 'approve', S.focus);
  if ((e.key === 'j' || e.key === 'ArrowDown') && S.screen === 'brain') { S.focus = Math.min(S.directives.length - 1, S.focus + 1); renderDirectives(); }
  if ((e.key === 'k' || e.key === 'ArrowUp') && S.screen === 'brain') { S.focus = Math.max(0, S.focus - 1); renderDirectives(); }
});
window.addEventListener('hashchange', () => { const t = ALIAS[location.hash.slice(1)] || location.hash.slice(1); if (views[t] && t !== S.screen) show(t); });

(async () => {
  await refreshState();
  await pollTrace();
  const h0 = ALIAS[location.hash.slice(1)] || location.hash.slice(1); show(views[h0] ? h0 : 'brain');
  setInterval(pollTrace, 4200);
  setInterval(refreshState, 60000);
})();
})();
